/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**
**     @file      lin_cfg.c
**
**     @date      ¿ÀÈÄ 5:24:57, 2025. 5. 15
**
**     @brief     Hardware configuration file
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016 - 2017 NXP
**     All Rights Reserved.
**
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/

/*!
 * @file lin_cfg.c
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, Could be made static.
 * Function ld_read_by_id_callout is API and shall not be made static.
 * This API is declared in lin_cfg.c so that users can configure the response
 * for  Read by ID request.
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.9, An object should be defined at block
 * scope if its identifier only appears in a single function.
 * An object with static storage duration declared at block scope cannot be
 * accessed directly from outside the block. g_lin_hardware_ifc, g_lin_tl_descriptor_array,
 * timerGetTimeIntervalCallback are dependent on user configurations,
 * so they shall be declared in lin_cfg.c.
 */

#include "lin.h"


#if (SUPPORT_TRANSPORT_LAYER == 1U)
static lin_tl_pdu_data_t      LI0_tl_tx_queue_data[2];
static lin_tl_pdu_data_t      LI0_tl_rx_queue_data[2];

static lin_tl_pdu_data_t      LI1_tl_tx_queue_data[2];
static lin_tl_pdu_data_t      LI1_tl_rx_queue_data[2];

static lin_tl_pdu_data_t      LI2_tl_tx_queue_data[2];
static lin_tl_pdu_data_t      LI2_tl_rx_queue_data[2];
#endif /* end (SUPPORT_TRANSPORT_LAYER == 1U) */

const l_ifc_handle g_lin_hardware_ifc[HARDWARE_INSTANCE_COUNT] = {LI0, LI1, LI2};
const l_u32 g_lin_virtual_ifc[LIN_NUM_OF_IFCS] = {0, 1, 2};
volatile l_u8 g_buffer_backup_data[8] = {0, 0, 0, 0, 0, 0, 0, 0};

/* definition and initialization of signal array */
volatile l_u8    g_lin_frame_data_buffer[LIN_FRAME_BUF_SIZE] =
{
  0x11 /* 0 : 00010001 */ /* start of frame LI0_EVNT_MASTER_COMMAND */

  ,0x00 /* 1 : 00000000 */

  ,0x00 /* 2 : 00000000 */

  ,0x00 /* 3 : 00000000 */

  ,0x00 /* 4 : 00000000 */

  ,0x00 /* 5 : 00000000 */

  ,0x00 /* 6 : 00000000 */

  ,0xf0 /* 7 : 11110000 */

  ,0x00 /* 8 : 00000000 */ /* start of frame LI0_FR_SLLR_STATUS */

  ,0x00 /* 9 : 00000000 */

  ,0x00 /* 10 : 00000000 */

  ,0x00 /* 11 : 00000000 */

  ,0x00 /* 12 : 00000000 */ /* start of frame LI0_FR_SLUD_STATUS */

  ,0x00 /* 13 : 00000000 */

  ,0x00 /* 14 : 00000000 */

  ,0x00 /* 15 : 00000000 */

  ,0x00 /* 16 : 00000000 */ /* start of frame LI0_FR_CLLR_STATUS */

  ,0x00 /* 17 : 00000000 */

  ,0x00 /* 18 : 00000000 */

  ,0x00 /* 19 : 00000000 */

  ,0x00 /* 20 : 00000000 */ /* start of frame LI0_FR_CLUD_STATUS */

  ,0x00 /* 21 : 00000000 */

  ,0x00 /* 22 : 00000000 */

  ,0x00 /* 23 : 00000000 */

  ,0x55 /* 24 : 01010101 */ /* start of frame LI0_EVNT_SPECIAL_COMMAND */

  ,0x11 /* 25 : 00010001 */

  ,0x15 /* 26 : 00010101 */ /* start of frame LI1_EVNT_MASTER_COMMAND */

  ,0x00 /* 27 : 00000000 */

  ,0x00 /* 28 : 00000000 */

  ,0x00 /* 29 : 00000000 */

  ,0x00 /* 30 : 00000000 */

  ,0x00 /* 31 : 00000000 */

  ,0x00 /* 32 : 00000000 */

  ,0xf0 /* 33 : 11110000 */

  ,0x00 /* 34 : 00000000 */ /* start of frame LI1_FR_CRLR_STATUS */

  ,0x00 /* 35 : 00000000 */

  ,0x00 /* 36 : 00000000 */

  ,0x00 /* 37 : 00000000 */

  ,0x00 /* 38 : 00000000 */ /* start of frame LI1_FR_CRUD_STATUS */

  ,0x00 /* 39 : 00000000 */

  ,0x00 /* 40 : 00000000 */

  ,0x00 /* 41 : 00000000 */

  ,0x00 /* 42 : 00000000 */ /* start of frame LI1_FR_SRLR_STATUS */

  ,0x00 /* 43 : 00000000 */

  ,0x00 /* 44 : 00000000 */

  ,0x00 /* 45 : 00000000 */

  ,0x00 /* 46 : 00000000 */ /* start of frame LI1_FR_SRUD_STATUS */

  ,0x00 /* 47 : 00000000 */

  ,0x00 /* 48 : 00000000 */

  ,0x00 /* 49 : 00000000 */

  ,0x55 /* 50 : 01010101 */ /* start of frame LI1_EVNT_SPECIAL_COMMAND */

  ,0x15 /* 51 : 00010101 */

  ,0x1f /* 52 : 00011111 */ /* start of frame LI2_EVNT_MASTER_COMMAND */

  ,0x00 /* 53 : 00000000 */

  ,0x00 /* 54 : 00000000 */

  ,0x18 /* 55 : 00011000 */

  ,0x00 /* 56 : 00000000 */

  ,0x00 /* 57 : 00000000 */

  ,0x18 /* 58 : 00011000 */

  ,0x00 /* 59 : 00000000 */

  ,0x10 /* 60 : 00010000 */ /* start of frame LI2_RR_CLLR_STATUS */

  ,0x00 /* 61 : 00000000 */

  ,0x00 /* 62 : 00000000 */

  ,0x00 /* 63 : 00000000 */

  ,0x10 /* 64 : 00010000 */ /* start of frame LI2_RR_CLUD_STATUS */

  ,0x00 /* 65 : 00000000 */

  ,0x00 /* 66 : 00000000 */

  ,0x00 /* 67 : 00000000 */

  ,0x10 /* 68 : 00010000 */ /* start of frame LI2_RR_CRLR_STATUS */

  ,0x00 /* 69 : 00000000 */

  ,0x00 /* 70 : 00000000 */

  ,0x00 /* 71 : 00000000 */

  ,0x10 /* 72 : 00010000 */ /* start of frame LI2_RR_CRUD_STATUS */

  ,0x00 /* 73 : 00000000 */

  ,0x00 /* 74 : 00000000 */

  ,0x00 /* 75 : 00000000 */

  ,0x55 /* 76 : 01010101 */ /* start of frame LI2_EVNT_SPECIAL_COMMAND */

  ,0x3e /* 77 : 00111110 */
};

/* definition and initialization of signal array */
volatile l_u8    g_lin_flag_handle_tbl[LIN_FLAG_BUF_SIZE] =
{
  0xFF /* 0: start of flag frame LI0_EVNT_MASTER_COMMAND */

  ,0xFF /* 1: start of flag frame LI0_FR_SLLR_STATUS */

  ,0xFF /* 2: */

  ,0xFF /* 3: */

  ,0xFF /* 4: start of flag frame LI0_FR_SLUD_STATUS */

  ,0xFF /* 5: */

  ,0xFF /* 6: */

  ,0xFF /* 7: start of flag frame LI0_FR_CLLR_STATUS */

  ,0xFF /* 8: */

  ,0xFF /* 9: */

  ,0xFF /* 10: start of flag frame LI0_FR_CLUD_STATUS */

  ,0xFF /* 11: */

  ,0xFF /* 12: */

  ,0xFF /* 13: start of flag frame LI0_EVNT_SPECIAL_COMMAND */

  ,0xFF /* 14: start of flag frame LI1_EVNT_MASTER_COMMAND */

  ,0xFF /* 15: start of flag frame LI1_FR_CRLR_STATUS */

  ,0xFF /* 16: */

  ,0xFF /* 17: */

  ,0xFF /* 18: start of flag frame LI1_FR_CRUD_STATUS */

  ,0xFF /* 19: */

  ,0xFF /* 20: */

  ,0xFF /* 21: start of flag frame LI1_FR_SRLR_STATUS */

  ,0xFF /* 22: */

  ,0xFF /* 23: */

  ,0xFF /* 24: start of flag frame LI1_FR_SRUD_STATUS */

  ,0xFF /* 25: */

  ,0xFF /* 26: */

  ,0xFF /* 27: start of flag frame LI1_EVNT_SPECIAL_COMMAND */

  ,0xFF /* 28: start of flag frame LI2_EVNT_MASTER_COMMAND */

  ,0xFF /* 29: start of flag frame LI2_RR_CLLR_STATUS */

  ,0xFF /* 30: */

  ,0xFF /* 31: */

  ,0xFF /* 32: start of flag frame LI2_RR_CLUD_STATUS */

  ,0xFF /* 33: */

  ,0xFF /* 34: */

  ,0xFF /* 35: start of flag frame LI2_RR_CRLR_STATUS */

  ,0xFF /* 36: */

  ,0xFF /* 37: */

  ,0xFF /* 38: start of flag frame LI2_RR_CRUD_STATUS */

  ,0xFF /* 39: */

  ,0xFF /* 40: */

  ,0xFF /* 41: start of flag frame LI2_EVNT_SPECIAL_COMMAND */
};

/* definition and initialization for flag of frame */
volatile l_bool g_lin_frame_flag_handle_tbl[LIN_NUM_OF_FRMS] = {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false};

/*************************** Frame flag for updating signal in frame ****************/
volatile l_u8 g_lin_frame_updating_flag_tbl[LIN_NUM_OF_FRMS] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};



/*****************************sporadic frame*****************************/
/*all sporadic frames for master node*/
/**********************************  Frame table **********************************/
static const lin_frame_t lin_frame_tbl[LIN_NUM_OF_FRMS] ={

    { LIN_FRM_UNCD, 8, LIN_RES_PUB, 0, 0, 1   , (lin_associate_frame_t*)0 }

   ,{ LIN_FRM_UNCD, 4, LIN_RES_SUB, 8, 1, 3 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 4, LIN_RES_SUB, 12, 4, 3 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 4, LIN_RES_SUB, 16, 7, 3 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 4, LIN_RES_SUB, 20, 10, 3 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 2, LIN_RES_PUB, 24, 13, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_DIAG, 8, LIN_RES_PUB, 0, 0, 0 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_DIAG, 8, LIN_RES_SUB, 0, 0, 0 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 8, LIN_RES_PUB, 26, 14, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 4, LIN_RES_SUB, 34, 15, 3 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 4, LIN_RES_SUB, 38, 18, 3 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 4, LIN_RES_SUB, 42, 21, 3 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 4, LIN_RES_SUB, 46, 24, 3 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 2, LIN_RES_PUB, 50, 27, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_DIAG, 8, LIN_RES_PUB, 0, 0, 0 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_DIAG, 8, LIN_RES_SUB, 0, 0, 0 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 8, LIN_RES_PUB, 52, 28, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 4, LIN_RES_SUB, 60, 29, 3 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 4, LIN_RES_SUB, 64, 32, 3 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 4, LIN_RES_SUB, 68, 35, 3 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 4, LIN_RES_SUB, 72, 38, 3 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 2, LIN_RES_PUB, 76, 41, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_DIAG, 8, LIN_RES_PUB, 0, 0, 0 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_DIAG, 8, LIN_RES_SUB, 0, 0, 0 , (lin_associate_frame_t*)0 }
  
};

static l_u8 LI0_lin_configuration_RAM[LI0_LIN_SIZE_OF_CFG]= {0x00, 0x11, 0x12, 0x13, 0x14, 0x15, 0x00, 0x3C, 0x3D ,0xFF};

static l_u8 LI1_lin_configuration_RAM[LI1_LIN_SIZE_OF_CFG]= {0x00, 0x21, 0x22, 0x23, 0x24, 0x25, 0x00, 0x3C, 0x3D ,0xFF};

static l_u8 LI2_lin_configuration_RAM[LI2_LIN_SIZE_OF_CFG]= {0x00, 0x31, 0x32, 0x33, 0x34, 0x35, 0x00, 0x3C, 0x3D ,0xFF};

static const l_u16  LI0_lin_configuration_ROM[LI0_LIN_SIZE_OF_CFG]= {0x0000, 0x11, 0x12, 0x13, 0x14, 0x15, 0x00, 0x3C, 0x3D ,0xFFFF};
static const l_u16  LI1_lin_configuration_ROM[LI1_LIN_SIZE_OF_CFG]= {0x0000, 0x21, 0x22, 0x23, 0x24, 0x25, 0x00, 0x3C, 0x3D ,0xFFFF};
static const l_u16  LI2_lin_configuration_ROM[LI2_LIN_SIZE_OF_CFG]= {0x0000, 0x31, 0x32, 0x33, 0x34, 0x35, 0x00, 0x3C, 0x3D ,0xFFFF};


/********************** Go to sleep Initialization *************************/
/* Delay of this schedule table is: (1.4*(34+10*(8+1))*1000/LIN_speed+jitter) ms */
/* then rounded up to a value is multiple of time base */
static const lin_schedule_data_t LI0_lin_gotosleep_data[1] = {
   {LI0_MasterReq, 2, {0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}}
};

/********************** Go to sleep Initialization *************************/
/* Delay of this schedule table is: (1.4*(34+10*(8+1))*1000/LIN_speed+jitter) ms */
/* then rounded up to a value is multiple of time base */
static const lin_schedule_data_t LI1_lin_gotosleep_data[1] = {
   {LI1_MasterReq, 2, {0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}}
};

/********************** Go to sleep Initialization *************************/
/* Delay of this schedule table is: (1.4*(34+10*(8+1))*1000/LIN_speed+jitter) ms */
/* then rounded up to a value is multiple of time base */
static const lin_schedule_data_t LI2_lin_gotosleep_data[1] = {
   {LI2_MasterReq, 2, {0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}}
};


/******************** Schedule table Initialization ************************/
static const lin_schedule_data_t LI0_SCHEDULER_EVNT_NORMAL_FR_DRV_data[5] = {

   {LI0_EVNT_MASTER_COMMAND, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_FR_SLLR_STATUS, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_FR_SLUD_STATUS, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_FR_CLLR_STATUS, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_FR_CLUD_STATUS, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
};
/******************** Schedule table Initialization ************************/
static const lin_schedule_data_t LI0_SCHEDULER_EVNT_SPECIAL_CMD_FR_DRV_data[2] = {

   {LI0_EVNT_SPECIAL_COMMAND, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_EVNT_SPECIAL_COMMAND, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
};
/******************** Schedule table Initialization ************************/
static const lin_schedule_data_t LI0_Diag_request_data[1] = {

   {LI0_MasterReq, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
};
/******************** Schedule table Initialization ************************/
static const lin_schedule_data_t LI0_Diag_response_data[1] = {

   {LI0_SlaveResp, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
};
/******************** Schedule table Initialization ************************/
static const lin_schedule_data_t LI1_SCHEDULER_EVNT_NORMAL_FR_PASS_data[5] = {

   {LI1_EVNT_MASTER_COMMAND, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI1_FR_CRLR_STATUS, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI1_FR_CRUD_STATUS, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI1_FR_SRLR_STATUS, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI1_FR_SRUD_STATUS, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
};
/******************** Schedule table Initialization ************************/
static const lin_schedule_data_t LI1_SCHEDULER_EVNT_SPECIAL_CMD_FR_PASS_data[2] = {

   {LI1_EVNT_SPECIAL_COMMAND, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI1_EVNT_SPECIAL_COMMAND, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
};
/******************** Schedule table Initialization ************************/
static const lin_schedule_data_t LI1_Diag_request_data[1] = {

   {LI1_MasterReq, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
};
/******************** Schedule table Initialization ************************/
static const lin_schedule_data_t LI1_Diag_response_data[1] = {

   {LI1_SlaveResp, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
};
/******************** Schedule table Initialization ************************/
static const lin_schedule_data_t LI2_SCHEDULER_EVNT_NORMAL_RR_CTR_data[5] = {

   {LI2_EVNT_MASTER_COMMAND, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI2_RR_CLLR_STATUS, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI2_RR_CLUD_STATUS, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI2_RR_CRLR_STATUS, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI2_RR_CRUD_STATUS, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
};
/******************** Schedule table Initialization ************************/
static const lin_schedule_data_t LI2_SCHEDULER_EVNT_SPECIAL_CMD_RR_CTR_data[2] = {

   {LI2_EVNT_SPECIAL_COMMAND, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI2_EVNT_SPECIAL_COMMAND, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
};
/******************** Schedule table Initialization ************************/
static const lin_schedule_data_t LI2_Diag_request_data[1] = {

   {LI2_MasterReq, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
};
/******************** Schedule table Initialization ************************/
static const lin_schedule_data_t LI2_Diag_response_data[1] = {

   {LI2_SlaveResp, 2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
};


/********************* Schedule table structure Initialization ***************/
static const lin_schedule_t lin_schedule_tbl[LIN_NUM_OF_SCHD_TBL] ={

   /*interface_name = LI0 */
   {0, LIN_SCH_TBL_NULL  ,(lin_schedule_data_t*)0 }
  
   ,{1, LIN_SCH_TBL_GO_TO_SLEEP  , &LI0_lin_gotosleep_data[0] }
  
   ,{1, LIN_SCH_TBL_DIAG  , &LI0_Diag_request_data[0] }
  
   ,{1, LIN_SCH_TBL_DIAG  , &LI0_Diag_response_data[0] }
  
   ,{5, LIN_SCH_TBL_NORM  , &LI0_SCHEDULER_EVNT_NORMAL_FR_DRV_data[0] }
  
   ,{2, LIN_SCH_TBL_NORM  , &LI0_SCHEDULER_EVNT_SPECIAL_CMD_FR_DRV_data[0] }
  
   ,{0, LIN_SCH_TBL_NULL  , (lin_schedule_data_t*)0 }
  
   ,{1, LIN_SCH_TBL_GO_TO_SLEEP  , &LI1_lin_gotosleep_data[0] }
  
   ,{1, LIN_SCH_TBL_DIAG  , &LI1_Diag_request_data[0] }
  
   ,{1, LIN_SCH_TBL_DIAG  , &LI1_Diag_response_data[0] }
  
   ,{5, LIN_SCH_TBL_NORM  , &LI1_SCHEDULER_EVNT_NORMAL_FR_PASS_data[0] }
  
   ,{2, LIN_SCH_TBL_NORM  , &LI1_SCHEDULER_EVNT_SPECIAL_CMD_FR_PASS_data[0] }
  
   ,{0, LIN_SCH_TBL_NULL  , (lin_schedule_data_t*)0 }
  
   ,{1, LIN_SCH_TBL_GO_TO_SLEEP  , &LI2_lin_gotosleep_data[0] }
  
   ,{1, LIN_SCH_TBL_DIAG  , &LI2_Diag_request_data[0] }
  
   ,{1, LIN_SCH_TBL_DIAG  , &LI2_Diag_response_data[0] }
  
   ,{5, LIN_SCH_TBL_NORM  , &LI2_SCHEDULER_EVNT_NORMAL_RR_CTR_data[0] }
  
   ,{2, LIN_SCH_TBL_NORM  , &LI2_SCHEDULER_EVNT_SPECIAL_CMD_RR_CTR_data[0] }
  
};
/****************************LIN interface configuration ****************************/
const lin_protocol_user_config_t g_lin_protocol_user_cfg_array[LIN_NUM_OF_IFCS] = {

    /* Interface_name = LI0 */
    {
        .protocol_version = LIN_PROTOCOL_21,         /*lin_protocol_version */
        .language_version = LIN_PROTOCOL_21,         /*lin_language_version */
        .diagnostic_class = LIN_DIAGNOSTIC_CLASS_I,            /* LIN Diagnostic Class */
        .function = (bool)LIN_MASTER,                 /*  function LIN_MASTER*/

        .number_of_configurable_frames = 8,                            /*  num_of_frames */
        .frame_start = 0,                              /*  frame_start */
        .frame_tbl_ptr = lin_frame_tbl,                                          /*  frame_tbl */

        .list_identifiers_ROM_ptr = LI0_lin_configuration_ROM,       /*  *configuration_ROM */
        .list_identifiers_RAM_ptr = LI0_lin_configuration_RAM,       /*  *configuration_RAM */
        .max_idle_timeout_cnt =  10000,     /* Max Idle Timeout Count */
        .num_of_schedules = 6,                                  /*  num_of_schedules */
        .schedule_start = 0,                                  /*  schedule_start */
        .schedule_tbl = lin_schedule_tbl,             /* schedule_tbl */

        .slave_ifc_handle = INVALID_SLAVE_INDEX,
        .master_ifc_handle = LI0_Master,
        .lin_user_config_ptr = &lin1_InitConfig0,
#if (SUPPORT_TRANSPORT_LAYER == 1U)
        .tl_tx_queue_data_ptr = LI0_tl_tx_queue_data,
        .tl_rx_queue_data_ptr = LI0_tl_rx_queue_data,
        .max_message_length = 6             /* Max message length */
#endif /* end (SUPPORT_TRANSPORT_LAYER == 1U) */
    },
    /* Interface_name = LI1 */
    {
        .protocol_version = LIN_PROTOCOL_21,         /*lin_protocol_version */
        .language_version = LIN_PROTOCOL_21,         /*lin_language_version */
        .diagnostic_class = LIN_DIAGNOSTIC_CLASS_I,            /* LIN Diagnostic Class */
        .function = (bool)LIN_MASTER,                 /*  function LIN_MASTER */

        .number_of_configurable_frames = 8,                            /*  num_of_frames */
        .frame_start = 8,                              /*  frame_start */
        .frame_tbl_ptr = &lin_frame_tbl[0],                                          /*  frame_tbl */

        .list_identifiers_ROM_ptr = LI1_lin_configuration_ROM,       /*  *configuration_ROM */
        .list_identifiers_RAM_ptr = LI1_lin_configuration_RAM,       /*  *configuration_RAM */
        .max_idle_timeout_cnt =  10000,     /* Max Idle Timeout Count */
        .num_of_schedules = 6,                                  /*  num_of_schedules */
        .schedule_start = 6,                                  /*  schedule_start */
        .schedule_tbl = lin_schedule_tbl,             /* schedule_tbl */

        .slave_ifc_handle = INVALID_SLAVE_INDEX,
        .master_ifc_handle = LI1_Master,
        .lin_user_config_ptr = &lin2_InitConfig0,
#if (SUPPORT_TRANSPORT_LAYER == 1U)
        .tl_tx_queue_data_ptr = LI1_tl_tx_queue_data,
        .tl_rx_queue_data_ptr = LI1_tl_rx_queue_data,
        .max_message_length = 6             /* Max message length */
#endif /* end (SUPPORT_TRANSPORT_LAYER == 1U) */
    }
,
    /* Interface_name = LI2 */
    {
        .protocol_version = LIN_PROTOCOL_21,         /*lin_protocol_version */
        .language_version = LIN_PROTOCOL_21,         /*lin_language_version */
        .diagnostic_class = LIN_DIAGNOSTIC_CLASS_I,            /* LIN Diagnostic Class */
        .function = (bool)LIN_MASTER,                 /*  function LIN_MASTER */

        .number_of_configurable_frames = 8,                            /*  num_of_frames */
        .frame_start = 16,                              /*  frame_start */
        .frame_tbl_ptr = &lin_frame_tbl[0],                                          /*  frame_tbl */

        .list_identifiers_ROM_ptr = LI2_lin_configuration_ROM,       /*  *configuration_ROM */
        .list_identifiers_RAM_ptr = LI2_lin_configuration_RAM,       /*  *configuration_RAM */
        .max_idle_timeout_cnt =  10000,     /* Max Idle Timeout Count */
        .num_of_schedules = 6,                                  /*  num_of_schedules */
        .schedule_start = 12,                                  /*  schedule_start */
        .schedule_tbl = lin_schedule_tbl,             /* schedule_tbl */

        .slave_ifc_handle = INVALID_SLAVE_INDEX,
        .master_ifc_handle = LI2_Master,
        .lin_user_config_ptr = &lin3_InitConfig0,
#if (SUPPORT_TRANSPORT_LAYER == 1U)
        .tl_tx_queue_data_ptr = LI2_tl_tx_queue_data,
        .tl_rx_queue_data_ptr = LI2_tl_rx_queue_data,
        .max_message_length = 6             /* Max message length */
#endif /* end (SUPPORT_TRANSPORT_LAYER == 1U) */
    }

};

/*FUNCTION**********************************************************************
 *
 * Function Name : ld_read_by_id_callout
 * Description   : This function is an example of response; real implementation is application-dependent
 *                 You can use one of the following define to set PCI of response frame for
 *                 this service to the correct value
 * Implements    : ld_read_by_id_callout_Activity
 *END**************************************************************************/

l_u8 ld_read_by_id_callout(l_ifc_handle iii, l_u8 id, l_u8 *data)
{
    l_u8 retval = LD_NEGATIVE_RESPONSE;

    /* Get the current configuration */
    const lin_protocol_user_config_t  *prot_user_config_ptr = &g_lin_protocol_user_cfg_array[iii];

    if (prot_user_config_ptr->function == (bool)LIN_SLAVE)
    {
        /* Following code is an example - Real implementation is application-dependent */
        /* the handling does essentially depend on the id of the requested item */
        /* This example implement with ID = 32 - LIN_READ_USR_DEF_MIN */
        if (id == LIN_READ_USR_DEF_MIN)
        {
            /*
            * id received is user defined 32
            */
            /* A positive response is ready to be sent to the user defined request */
            data[0] = (l_u8) (id + 1U);    /* Data user define */
            data[1] = (l_u8) (id + 2U);    /* Data user define */
            data[2] = (l_u8) (id + 3U);    /* Data user define */
            data[3] = (l_u8) (id + 4U);    /* Data user define */
            data[4] = (l_u8) (id + 5U);    /* Data user define */
            retval = LD_POSITIVE_RESPONSE;
        }
        else
        {
            /*
            * id received is user defined 63 - no response
            */
        }
    } /* End (conf->function == _SLAVE_) */
   return retval;
}

